name: CI
on: [push]
jobs:
  #testing:
  #another_test_job:
  #  runs-on: ubuntu-latest
  #  container: ../actions/dind-multiarch/dind-arch.Dockerfile
  #  services:
  #    dind_service:
  #      - name: Example step
  #        run: |
  #          env
  #          uname -a
  #          uname -r
  #          echo $SHELL

  #testing: build use action
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/dind-multiarch
      - name: Print env
        run: |
          env
          uname -a
          uname -r
          echo $SHELL
          find /usr/bin

  #testing: build image with buildx
  #build_image:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Set up docker buildx context
  #      uses: docker/setup-buildx-action@v3
  #    - name: Build and push
  #      uses: docker/build-push-action@v3
  #      with:
  #        push: false
  #        file: ./.github/actions/dind-multiarch/dind-arch.Dockerfile
  #        tags: dind-arch:${{ github.run_number }}
  #        outputs: type=docker,dest=./dind-arch.tar
  #        cache-from: type=registry,ref=dind-arch:${{ github.run_number }}
  #        cache-to: type=registry,ref=dind-arch:${{ github.run_number }}

