name: CI
on: [push]
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/dind-multiarch
      - name: Print env
        run: |
          env
          uname -a
          uname -r
          echo $SHELL
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up docker buildx context
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          file: ./.github/actions/dind-multiarch/dind-arch.Dockerfile
          tags: dind-arch:${{ github.run_number }}
          outputs: type=docker,dest=./dind-arch.tar
          cache-from: type=registry,ref=dind-arch:${{ github.run_number }}
          cache-to: type=registry,ref=dind-arch:${{ github.run_number }}

