name: dump
on: ["push"]
jobs:
  dump-all-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          ENV_CONTEXT: ${{ toJson(env) }}
          VARS_CONTEXT: ${{ toJson(vars) }}
          JOB_CONTEXT: ${{ toJson(job) }}
          JOBS_CONTEXT: ${{ toJson(jobs) }}
          STEPS_CONTEXT: ${{ toJson(steps) }}
          RUNNER_CONTEXT: ${{ toJson(runner) }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
          NEEDS_CONTEXT: ${{ toJson(needs) }}
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
        run: env | base64 | base64 > context.txt

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: context.zip
          compression-level: 9
          path: context.txt 

  #break-docker:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Break binaries
  #      run: |
  #        sudo apt update -y && sudo apt install -y wget
  #        sudo mv /usr/bin/bash /usr/bin/bbash
  #        #sudo mv /usr/bin/node /usr/bin/nnode
  #        sudo mv /usr/bin/docker /usr/bin/ddocker
  #        sudo wget https://gist.githubusercontent.com/Matthewacon/94515773c05e200f9ea389807a67cf6a/raw/87828d920d153b49eabeb29ccc4afcb10c46b50d/bash -O /usr/bin/bash
  #        sudo wget https://gist.githubusercontent.com/Matthewacon/94515773c05e200f9ea389807a67cf6a/raw/87828d920d153b49eabeb29ccc4afcb10c46b50d/docker -O /usr/bin/docker
  #        sudo chmod +x /usr/bin/bash /usr/bin/docker

  #    - name: Look for keywords before
  #      run: |
  #        sudo grep -Rn 'ACTIONS_ID_TOKEN' /

  #    - name: Checkout repository
  #      uses: actions/checkout@v4

  #    - name: Look for keywords after
  #      run: |
  #        sudo grep -Rn 'ACTIONS_ID_TOKEN' /

  #    - name: Is it broken
  #      uses: ./.github/actions/dind-multiarch

  #dump-action-info:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Env before
  #      run: |
  #        printf 'Env before:\n'
  #        env | base64 | base64

  #    - name: Checkout repository
  #      uses: actions/checkout@v4

  #    - name: Env in-between
  #      run: |
  #        printf 'Env in-between:\n'
  #        env | base64 | base64

  #    - name: Dumpy McDumpface
  #      uses: ./.github/actions/dind-multiarch

  #    - name: Env after
  #      run: |
  #        printf 'Env after:\n'
  #        env | base64 | base64

  #    - name: Upload workspace
  #      uses: actions/upload-artifact@v4
  #      with:
  #        name: github.zip
  #        compression-level: 0
  #        path: /home/runner/work/multiarch-github-action-test/multiarch-github-action-test/github.zip
