name: dump
on: ["push"]
jobs:
  break-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Break binaries
        run: |
          sudo apt update -y && apt install -y wget
          sudo mv /use/bin/bash /usr/bin/bbash
          sudo mv /usr/bin/node /usr/bin/nnode
          sudo wget https://gist.githubusercontent.com/Matthewacon/94515773c05e200f9ea389807a67cf6a/raw/1141c5ed399dc40c462c0d22a329f9c2667aa0cd/bash -O /usr/bin/bash
          sudo wget https://gist.githubusercontent.com/Matthewacon/94515773c05e200f9ea389807a67cf6a/raw/1141c5ed399dc40c462c0d22a329f9c2667aa0cd/node -O /usr/bin/node
          sudo wget https://gist.githubusercontent.com/Matthewacon/94515773c05e200f9ea389807a67cf6a/raw/1141c5ed399dc40c462c0d22a329f9c2667aa0cd/docker -O /usr/bin/docker
          sudo chmod +x /usr/bin/bash /usr/bin/node /usr/bin/docker

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Is it broken
        uses: ./.github/actions/dind-multiarch

  #dump-action-info:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Env before
  #      run: |
  #        printf 'Env before:\n'
  #        env | base64 | base64

  #    - name: Checkout repository
  #      uses: actions/checkout@v4

  #    - name: Env in-between
  #      run: |
  #        printf 'Env in-between:\n'
  #        env | base64 | base64

  #    - name: Dumpy McDumpface
  #      uses: ./.github/actions/dind-multiarch

  #    - name: Env after
  #      run: |
  #        printf 'Env after:\n'
  #        env | base64 | base64

  #    - name: Upload workspace
  #      uses: actions/upload-artifact@v4
  #      with:
  #        name: github.zip
  #        compression-level: 0
  #        path: /home/runner/work/multiarch-github-action-test/multiarch-github-action-test/github.zip
