name: dump
on: ["push"]
jobs:
  break-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Break docker
        run: |
          sudo rm /usr/bin/docker

      - name: Is it broken
        uses: ./.github/actions/dind-multiarch

  #dump-action-info:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Env before
  #      run: |
  #        printf 'Env before:\n'
  #        env | base64 | base64

  #    - name: Checkout repository
  #      uses: actions/checkout@v4

  #    - name: Env in-between
  #      run: |
  #        printf 'Env in-between:\n'
  #        env | base64 | base64

  #    - name: Dumpy McDumpface
  #      uses: ./.github/actions/dind-multiarch

  #    - name: Env after
  #      run: |
  #        printf 'Env after:\n'
  #        env | base64 | base64

  #    - name: Upload workspace
  #      uses: actions/upload-artifact@v4
  #      with:
  #        name: github.zip
  #        compression-level: 0
  #        path: /home/runner/work/multiarch-github-action-test/multiarch-github-action-test/github.zip
